# I have no idea what I'm doing
name: Automatic Build

on:
  push:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  pull_request:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']

jobs:
  build-windows:
    name: Windows (${{ matrix.sys }})
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - { sys: mingw32, env: i686, ruby-prefix: msvcrt }
        - { sys: mingw64, env: x86_64, ruby-prefix: x64-msvcrt }
        - { sys: ucrt64, env: ucrt-x86_64, ruby-prefix: x64-ucrt }

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (${{ matrix.sys }})
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: >-
            base-devel
            git
            vim
            ruby
            mingw-w64-${{ matrix.env }}-gcc
            mingw-w64-${{ matrix.env }}-autotools
            mingw-w64-${{ matrix.env }}-cmake
            mingw-w64-${{ matrix.env }}-meson

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: windows/build-${{ matrix.sys }}
          key: windows-${{ matrix.sys }}-${{ hashFiles('windows/Makefile') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/windows
        shell: msys2 {0}
        run: make LTO=0

      - name: Build ModShot
        shell: msys2 {0}
        run: |
          source windows/vars.sh
          meson setup build --prefix="$GITHUB_WORKSPACE/build/artifact"
          meson compile -Cbuild
          meson install -Cbuild

      - name: Prepare artifact
        working-directory: ${{ github.workspace }}/build/artifact
        shell: msys2 {0}
        run: |
          strip ./*.exe
          strip ./*.dll
          strip ./rubylib/3.1.0/*/*.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MKXP-Z_Windows_${{ matrix.sys }}_${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}_${{ steps.shorten-sha.outputs.sha }}
          path: build/artifact


  build-linux-native:
    name: Ubuntu 22.04 x86_64
    runs-on: ubuntu-22.04
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            linux/build-x86_64
            linux/downloads
          key: lin-x86_64-${{ hashFiles('linux/Makefile') }}

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install git wget build-essential cmake meson autoconf automake libtool pkg-config ruby bison xxd zlib1g-dev libbz2-dev xorg-dev libgl1-mesa-dev libasound2-dev libpulse-dev -y

      - name: Build everything else
        run: |
          cd linux
          make

      - name: Build executable
        run: |
          source linux/vars.sh
          meson setup build --bindir=. --prefix=$GITHUB_WORKSPACE/build/local
          cd build
          ninja
          ninja install

      - name: Prepare archive
        run: |
          cd build/local
          cp -r ../../linux/build-x86_64/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux.ubuntu.22.04.x86_64.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/local

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Remove pre-existing homebrew packages
        run: brew remove --force $(brew list)

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            macos/Dependencies/build-macosx-x86_64
            macos/Dependencies/build-macosx-arm64
            macos/Dependencies/build-macosx-universal
            macos/Dependencies/downloads
          key: mac-${{ hashFiles('macos/Dependencies/*.make', 'macos/Dependencies/*.sh') }}

      - name: Install Homebrew tools
        run: |
          cd macos/Dependencies
          brew bundle

      - name: Build all dependencies
        run: |
          cd macos/Dependencies
          ./setup.sh

      - name: Build app
        run: |
          cd macos
          xcodebuild -project mkxp-z.xcodeproj -configuration "Release" -scheme "Universal" -derivedDataPath "$GITHUB_WORKSPACE/build"

      - name: Compress app
        run: |
          cd build/Build/Products/Release
          cp ../../../../assets/LICENSE.mkxp-z-with-https.txt ./Z-universal.app/
          ditto -c -k --sequesterRsrc --keepParent Z-universal.app Z-universal.app.zip

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.macos.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/Build/Products/Release/Z-universal.app.zip
